### ISSUE TITLE
install_github failing

### ISSUE THREAD

**Issue by jefshe** [Microsoft/AzureSMR#105]
I recently tried to update this R package and something seems to be broken:
```R
> devtools::install_github('Microsoft/AzureSMR')
Downloading GitHub repo Microsoft/AzureSMR@master
from URL https://api.github.com/repos/Microsoft/AzureSMR/zipball/master
Error in read.dcf(path_desc) : Line starting ') ...' is malformed!
Calls: <Anonymous> ... as.package -> load_pkg_description -> as.list -> read.dcf
Execution halted
```

I did some quick googling and it seems to be related to non-ASCII characters in the package description

**Comment by richcalaway** [comment]
Starting a line with a ")" seems to be a no-no--fixed by moving the closing parenthesis of the Authors@R field to the end of the previous line.
