### ISSUE TITLE
Return TRUE for if function calls are successful, rather than "Done"

### ISSUE THREAD

**Issue by gjwgit** [Microsoft/AzureSMR#31]
What does the "R" in the status codes mean? It's not listed.

```r
> azureStopVM(azureActiveContext=sc, resourceGroup=RG, vmName=vmnames[1])
azureStopVM: Request Submitted:  2016-12-22 09:10:37
Updating(U), deallocating(D), starting(S), Stopped/Deallocated(-) 
**R**DDDDDDDDDDDDDDDDDDDD
Finished Deallocated Sucessfully:  2016-12-22 09:12:20
Finished:  2016-12-22 09:12:20
[1] "Done"
```

Do we need to return "Done"? Just a silent TRUE might be okay. This probably applies across many other of the functions too.

Similarly - what is A in the following:

```r
azureDeployTemplate: Request Submitted:  2016-12-22 11:26:14
Running(R), Succeeded(S)
**A**RRRR
```

**Comment by Alanwe** [comment]
Happy to move "Done" to TRUE , however I think we should ensure there is an informational message.

A means accepted, we should add it to the description

**Comment by andrie** [comment]
I'm slowly working through all the functions to return logical values.

**Comment by andrie** [comment]
Migration now complete. Closing this issue.
