### ISSUE TITLE
Support blob functions without authentication

### ISSUE THREAD

**Issue by andrie** [Microsoft/AzureSMR#44]
As mentioned in #41, some functions don't require authentication against the Azure Service Manager. Specifically, blob storage functions will work given only the storage key.

By supporting a version of the function that does not enforce supplying the `activeAzureContext` argument, we can improve ease-of-use for certain use cases.

I will create a feature branch to test this functionality, prioritizing the following functions:

* `azureListStorageBlobs()`
* azureGetBlob()`

**Comment by Alanwe** [comment]
Great plan Andire.  Also we need to check the blob read/write for some data types.
