### ISSUE TITLE
Console messages from azureGetBlob

### ISSUE THREAD

**Issue by jrowen** [Microsoft/AzureSMR#45]
This is more of a feature request, but it would be great to be able to suppress messages from `azureGetBlob` (maybe via the existing `verbose` parameter).  If the messages stay, it would be nice to append a new line character to the current message (see [`cat`](https://github.com/Microsoft/AzureSMR/blob/master/R/AzureBlob.R#L363)).

**Comment by andrie** [comment]
This was fixed as a side effect of dbd313b (#46)
