### ISSUE TITLE
azureRunScriptAction() returns 404

### ISSUE THREAD

**Issue by akzaidi** [Microsoft/AzureSMR#58]
### Example

```
azureRunScriptAction(sc, 
                     scriptname = "installPackages",
                     scriptURL = "http://mrsactionscripts.blob.core.windows.net/rpackages-v01/InstallRPackages.sh",
                     workerNode = TRUE, edgeNode = TRUE,
                     parameters = "useCRAN stringr")
```

Returns:
```bash
Error in azureRunScriptAction(... 
  Error: Return code 404
```

### Possible Bug Location

It looks like the issue is in the following `httr` call:

```
  r <- POST(URL, add_headers(.headers = c(Host = "management.azure.com", 
    Authorization = ATI, `Content-type` = "application/json")), 
    body = bodyI, encode = "json", verbosity)
```

**Comment by andrie** [comment]
We now have a function to trap and report on Azure errors:

```r
stopWithAzureError(r)
```

I will get to HDI functions eventually. Right now I'm gradually refactoring and fixing issues earlier in the code base.

**Comment by andrie** [comment]
I've started working on refactoring the code for running script actions.  This is not yet checked into the dev branch, but here is my hunch.

1. When I run your code the first time, it completes without any problem.
1. If I then submit this again, I get an error

```
Error: azureRunScriptAction()
BadRequest
Scripts with the following names already exist in the persisted
script list: installPackages
Return code: 400
```

My next action is to expose this error and print a friendly message.

**Comment by andrie** [comment]
@akzaidi Can you please test again?

**Comment by akzaidi** [comment]
Does work, thanks ! One weird issue, it prints the following Error:
`Error: Provide a valid resourceGroup argument, or set using createAzureContext()`

Example usage:

```
> azureRunScriptAction(sc, resourceGroup = "alizaidi", clustername = "azrsparkdev",
                      scriptname = "installlubridate",
                      scriptURL = "http://mrsactionscripts.blob.core.windows.net/rpackages-v01/InstallRPackages.sh",
                      workerNode = TRUE, edgeNode = TRUE,
                      parameters = "useCRAN lubridate")
Accepted
Script action request submitted: 2017-05-31 11:42:45
Key: A - accepted, (.) - in progress, S - succeeded, E - error, F - failed
Error: Provide a valid resourceGroup argument, or set using createAzureContext()
```

**Comment by andrie** [comment]
Thanks for the report.

So the error happens when `pollStatusScriptAction ()` passes the request to `azureScriptActionHistory()` - this requires the `resourceGroup`.

**Comment by andrie** [comment]
I've pushed a fix for this to the dev branch.
