### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by BuckWoody** [Microsoft/AzureSMR#60]
It might be a good idea to actually change the blurb on the github from

> "R Package for managing a selection of Azure resources. Targeted at Data Scientists who need to control Azure Resources without **needing to both Administrators**. APIs include Storage Blobs, HDInsight(Nodes, Hive, Spark), ARM, VMs" 

to the more grammatically correct 

> "R Package for managing a selection of Azure resources. Targeted at Data Scientists who need to control Azure Resources without needing to involve Administrators. APIs include Storage Blobs, HDInsight(Nodes, Hive, Spark), ARM, VMs"

**Comment by andrie** [comment]
That's what happens when sales people develop code in their spare time :-)

Thanks for reporting and the suggestion.

PS. We welcome pull requests for documentation improvement!
