### ISSUE TITLE
Support accessing storage API without an azureActiveObject

### ISSUE THREAD

**Issue by Alanwe** [Microsoft/AzureSMR#76]
Some functions such as the Storage BLOB API don't necessarily need AD permissions to use the API. We should ensure that we don't check for AD tokens if a StorageKey has been provided.

**Comment by andrie** [comment]
This is a duplicate of #44 and has already been implemented.

The usage is to pass `azureActiveContext = NULL` as the first argument of all the storage functions.

The documentation for this should be improved.
